version: "0.1-alpha-{build}"

# Fix line endings in Windows. (runs before repo cloning)
init:
  - git config --global core.autocrlf input

# this turns of AppVeyor automatic searching for test-assemblies, not the actual testing
test: off

build_script:
  #- set BUILD_NUMBER=%APPVEYOR_BUILD_NUMBER% #temp
  - build.cmd

environment:
  XUNIT_TEST_VISITOR: Xunit.KRunner.AppVeyor
  #BUILD_NUMBER: "$(build)"

#artifacts:
#  - path: artifacts\build\*.nupkg